{% set name = "verstr" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/verstr-{{ version }}.tar.gz
  sha256: 64b47fe4e01778d073796ca76cf8d996a841f15d7c444369e5524f836a5056f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=40.9.0
    - wheel
    - setuptools_scm >=6.2
  run:
    - packaging
    - python >={{ python_min }}

test:
  imports:
    - verstr
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/BRGM/verstr
  summary: Make comparing version strings super simple.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fsmaibrgm
